djangocms_stories/urls.py
from django.urls import path

from .feeds import FBInstantArticles, LatestEntriesFeed, TagFeed
from .settings import get_setting
from .views import (
    AuthorEntriesView,
    CategoryEntriesView,
    CategoryListView,
    PostArchiveView,
    PostDetailView,
    PostListView,
    TaggedListView,
)

app_name = "djangocms_stories"
urlpatterns = [
    path("", PostListView.as_view(), name="posts-latest"),
    path("category/", CategoryListView.as_view(), name="categories-all"),
    path("category/<str:category>/", CategoryEntriesView.as_view(), name="posts-category"),
    path("feed/", LatestEntriesFeed(), name="posts-latest-feed"),
    path("feed/fb/", FBInstantArticles(), name="posts-latest-feed-fb"),
    path("<int:year>/", PostArchiveView.as_view(), name="posts-archive"),
    path("<int:year>/<int:month>/", PostArchiveView.as_view(), name="posts-archive"),
    path("author/<str:username>/", AuthorEntriesView.as_view(), name="posts-author"),
    path("tag/<slug:tag>/", TaggedListView.as_view(), name="posts-tagged"),
    path("tag/<slug:tag>/feed/", TagFeed(), name="posts-tagged-feed"),
]
permalink_urls = get_setting("PERMALINK_URLS")
for urlconf in permalink_urls.values():
    urlpatterns.append(
        path(urlconf, PostDetailView.as_view(), name="post-detail"),
    )

djangocms_stories/templates/djangocms_stories/base.html
{% extends CMS_TEMPLATE|default:"base.html" %}

{% block meta %}
    {% comment %}
    This is needed if you can't add ``{% include "meta/meta.html" %}`` in the django CMS template attached to the blog
    page or if you use djangocms-page-meta.

    Please check the documentation at https://djangocms-blog.readthedocs.io/en/latest/features/meta.html for more
    details about the correct template configuration for social media tags rendering.
    {% endcomment %}
    {% if meta %}
        {% include "meta/meta.html" %}
    {% else %}
        {{ block.super }}
    {% endif %}
{% endblock meta %}

{% block content %}
<div class="app app-blog">
    {% block content_blog %}{% endblock %}
</div>
{% endblock content %}

djangocms_stories/templates/djangocms_stories/category_list.html
{% extends "djangocms_stories/base.html" %}
{% load i18n easy_thumbnails_tags cms_tags %}{% spaceless %}

{% block canonical_url %}<link rel="canonical" href="{{ view.get_view_url }}"/>{% endblock canonical_url %}

{% block content_blog %}
<section class="blog-list">
    {% for category in category_list %}
        {% include "djangocms_stories/includes/category_item.html" with category=category image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
    {% empty %}
        <p class="blog-empty">{% trans "No article found." %}</p>
    {% endfor %}
    {% if author or archive_date or tagged_entries %}
    <p class="blog-back"><a href="{% url 'djangocms_stories:posts-latest' %}">{% trans "Back" %}</a></p>
    {% endif %}
    {% if is_paginated %}
    <nav class="{% firstof css_grid instance.css_grid %} pagination">
        {% if page_obj.has_previous %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
        {% endif %}
        <span class="current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
        {% endif %}
    </nav>
    {% endif %}
</section>
{% endblock %}
{% endspaceless %}

djangocms_stories/templates/djangocms_stories/post_archive.html
{% extends "djangocms_stories/post_list.html" %}

djangocms_stories/templates/djangocms_stories/post_detail.html
{% extends "djangocms_stories/base.html" %}
{% load i18n easy_thumbnails_tags cms_tags %}

{% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
{% block title %}{{ post_content.title }}{% endblock %}

{% block content_blog %}{% spaceless %}
<article id="post-{{ post_content.slug }}" class="post-item post-detail">
    <header>
        <h2>{% render_model post_content "title" "title" %}</h2>
        {% if post_content.subtitle %}
            <h3>{% render_model post_content "subtitle" "subtitle" %}</h3>
        {% endif %}
        {% block post_meta %}
            {% block blog_meta %}
                {% include "djangocms_stories/includes/post_meta.html" %}
            {% endblock %}
        {% endblock %}
    </header>
    {% if post_content.post.app_config.use_placeholder and not post_content.post.main_image_id and post_content.media %}
        <div class="blog-visual">{% placeholder "media" %}</div>
    {% else %}
        <div class="blog-visual">
            {% thumbnail post_content.post.main_image post_content.post.full_image_options.size crop=post_content.post.full_image_options.crop upscale=post_content.post.full_image_options.upscale subject_location=post_content.post.main_image.subject_location as main_image %}
            <img src="{{ main_image.url }}" alt="{{ post_content.post.main_image.default_alt_text }}" width="{{ main_image.width }}" height="{{ main_image.height }}" />
        </div>
    {% endif %}
    {% endspaceless %}
    {% if post_content.post.app_config.use_placeholder and post_content.content %}
        <div class="blog-content">{% placeholder "content" %}</div>
    {% else %}
        <div class="blog-content">{% render_model post_content "post_text" "post_text" "" "safe" %}</div>
    {% endif %}
    {% if post_content.post.related.exists %}
        <section class="post-detail-list">
        {% for related in post_content.post.related.all %}
            {% include "djangocms_stories/includes/post_item.html" with post_content=related.get_content image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
        {% endfor %}
        </section>
    {% endif %}
</article>
{% endblock content_blog %}

djangocms_stories/templates/djangocms_stories/post_instant_article.html
{% load easy_thumbnails_tags cms_tags %}
<!doctype html>
<html lang="{{ post.get_current_language }}" prefix="op: http://media.facebook.com/op#">
  <head>
    <meta charset="utf-8">
    {% block canonical_url %}<link rel="canonical" href="{{ meta.url }}"/>{% endblock canonical_url %}
    <meta property="op:markup_version" content="v1.0">
  </head>
  <body>
    <article>
      <header>
        <h1>{{ post.title }}</h1>
        {% if post.subtitle %}
            <h2>{{ post.subtitle }}</h2>
        {% endif %}
        <time class="op-published" datetime="{{ post.date_published|date:"Y-m-d\TH:i:sO" }}">{{ post.date_published|date:"DATE_FORMAT" }}</time>
        <time class="op-modified" dateTime="{{ post.date_modified|date:"Y-m-d\TH:i:sO" }}">{{ post.date_modified|date:"DATE_FORMAT" }}</time>
        <address>
            <a {% if og_author_url %}rel="facebook" href="{{ og_author_url }}"{% endif %}>{{ post.get_author_name }}</a>
        </address>
        <figure>
            <img src="{{ meta.image }}" alt="{{ post.main_image.default_alt_text|default:'' }}" />
            {% if post.main_image.default_caption %}<figcaption>{{ post.main_image.default_caption }}</figcaption>{% endif %}
        </figure>
        <h3 class="op-kicker">{{ post.abstract|striptags|safe }}</h3>
      </header>
      {% if post.app_config.use_placeholder %}
      <div class="blog-content">{% render_placeholder post.content %}</div>
      {% else %}
      <div class="blog-content">{% render_model post "post_text" "post_text" "" "safe" %}</div>
      {% endif %}
    </article>
  </body>
</html>

djangocms_stories/templates/djangocms_stories/post_list.html
{% extends "djangocms_stories/base.html" %}
{% load i18n easy_thumbnails_tags cms_tags %}{% spaceless %}

{% block canonical_url %}<link rel="canonical" href="{{ view.get_view_url }}"/>{% endblock canonical_url %}

{% block content_blog %}
<section class="blog-list">
    {% block blog_title %}
    <header>
        <h2>
        {% if author %}{% trans "Articles by" %} {{ author.get_full_name }}
        {% elif archive_date %}{% trans "Archive" %} &ndash; {% if month %}{{ archive_date|date:'F' }} {% endif %}{{ year }}
        {% elif tagged_entries %}{% trans "Tag" %} &ndash; {{ tagged_entries|capfirst }}
        {% elif category %}{% trans "Category" %} &ndash; {% render_model category "name" %}{% endif %}
        </h2>
        {% if category.abstract %}
          <div class="category-abstract">
            {% render_model category "abstract" %}
          </div>
        {% endif %}
    </header>
    {% endblock %}
    {% for post_content in postcontent_list %}
        {% include "djangocms_stories/includes/post_item.html" with post_content=post_content image="true" TRUNCWORDS_COUNT=TRUNCWORDS_COUNT %}
    {% empty %}
    <p class="blog-empty">{% trans "No article found." %}</p>
    {% endfor %}
    {% if author or archive_date or tagged_entries %}
    <p class="blog-back"><a href="{% url 'djangocms_stories:posts-latest' %}">{% trans "Back" %}</a></p>
    {% endif %}
    {% if is_paginated %}
    <nav class="{% firstof css_grid instance.css_grid %} pagination">
        {% if page_obj.has_previous %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.previous_page_number }}">&laquo; {% trans "previous" %}</a>
        {% endif %}
        <span class="current">
            {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
            <a href="?{{ view.page_kwarg }}={{ page_obj.next_page_number }}">{% trans "next" %} &raquo;</a>
        {% endif %}
    </nav>
    {% endif %}
</section>
{% endblock %}
{% endspaceless %}

djangocms_stories/templates/djangocms_stories/post_structure.html
{% load cms_tags %}
{% placeholder 'media' %}
{% placeholder 'content' %}